# coding: utf-8

"""
    Swagger Spark

    This is a sample server Spark server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.  # noqa: E501

    OpenAPI spec version: 0.7.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.spark_submit_api import SparkSubmitApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSparkSubmitApi(unittest.TestCase):
    """SparkSubmitApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.spark_submit_api.SparkSubmitApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_spark_submit(self):
        """Test case for spark_submit

        You can running spark application by this API  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
