# coding: utf-8

"""
    wordcount_search11

    Apps that count the number of specific characters  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: ghwlchlaks@naver.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.spark_apps_api import SparkAppsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSparkAppsApi(unittest.TestCase):
    """SparkAppsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.spark_apps_api.SparkAppsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_wordcount_search11(self):
        """Test case for wordcount_search11

        Apps that count the number of specific characters  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
