# coding: utf-8

"""
    wordcount

    Apps that count the number of all characters  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: 4qazwsx@naver.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="wordcount",
    author_email="4qazwsx@naver.com",
    url="",
    keywords=["Swagger", "wordcount"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Apps that count the number of all characters  # noqa: E501
    """
)
