/*
 * wordcount_search
 * Apps that count the number of specific characters
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ghwlchlaks
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * running spark
 */
@ApiModel(description = "running spark")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-14T17:08:18.786+09:00")
public class Spark {
  @SerializedName("email")
  private String email = null;

  @SerializedName("data")
  private String data = null;

  @SerializedName("target")
  private String target = null;

  @SerializedName("user")
  private String user = null;

  @SerializedName("APP")
  private String APP = null;

  @SerializedName("--word")
  private String word = null;

  public Spark email(String email) {
    this.email = email;
    return this;
  }

   /**
   * your email
   * @return email
  **/
  @ApiModelProperty(example = "developer", required = true, value = "your email")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Spark data(String data) {
    this.data = data;
    return this;
  }

   /**
   * target data name
   * @return data
  **/
  @ApiModelProperty(example = "AtoZ.txt", required = true, value = "target data name")
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }

  public Spark target(String target) {
    this.target = target;
    return this;
  }

   /**
   * callback target (email or slack)
   * @return target
  **/
  @ApiModelProperty(example = "email", value = "callback target (email or slack)")
  public String getTarget() {
    return target;
  }

  public void setTarget(String target) {
    this.target = target;
  }

  public Spark user(String user) {
    this.user = user;
    return this;
  }

   /**
   * callback address
   * @return user
  **/
  @ApiModelProperty(example = "Your@email.com", value = "callback address")
  public String getUser() {
    return user;
  }

  public void setUser(String user) {
    this.user = user;
  }

  public Spark APP(String APP) {
    this.APP = APP;
    return this;
  }

   /**
   * target app name
   * @return APP
  **/
  @ApiModelProperty(example = "wordcount_search.py", required = true, value = "target app name")
  public String getAPP() {
    return APP;
  }

  public void setAPP(String APP) {
    this.APP = APP;
  }

  public Spark word(String word) {
    this.word = word;
    return this;
  }

   /**
   * Option to count the number of specific words (case sensitive)
   * @return word
  **/
  @ApiModelProperty(example = "A", value = "Option to count the number of specific words (case sensitive)")
  public String getWord() {
    return word;
  }

  public void setWord(String word) {
    this.word = word;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Spark spark = (Spark) o;
    return Objects.equals(this.email, spark.email) &&
        Objects.equals(this.data, spark.data) &&
        Objects.equals(this.target, spark.target) &&
        Objects.equals(this.user, spark.user) &&
        Objects.equals(this.APP, spark.APP) &&
        Objects.equals(this.word, spark.word);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, data, target, user, APP, word);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Spark {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    APP: ").append(toIndentedString(APP)).append("\n");
    sb.append("    word: ").append(toIndentedString(word)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

