/*
 * wordcount_search20
 * Apps that count the number of specific characters
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ghwlchlaks@naver.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
