/*
 * Swagger Spark
 * This is a sample server Spark server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 0.7.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Spark;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SparkSubmitApi
 */
@Ignore
public class SparkSubmitApiTest {

    private final SparkSubmitApi api = new SparkSubmitApi();

    
    /**
     * You can running spark application by this API
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sparkSubmitTest() throws ApiException {
        Spark body = null;
        api.sparkSubmit(body);

        // TODO: test validations
    }
    
}
