# coding: utf-8

# flake8: noqa
"""
    wordcount

    Apps that count the number of all characters  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: 4qazwsx@naver.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.spark import Spark
