/*
 * wordcount_search
 * Apps that count the number of specific characters
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ghwlchlaks
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.JSON;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SparkAppsApi
 */
@Ignore
public class SparkAppsApiTest {

    private final SparkAppsApi api = new SparkAppsApi();

    
    /**
     * Apps that count the number of specific characters
     *
     * Apps that count the number of specific characters
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void wordcountSearchTest() throws ApiException {
        JSON body = null;
        api.wordcountSearch(body);

        // TODO: test validations
    }
    
}
